version: '3.4'

services:
  smart-home-back-dev:
    image: 
    container_name: 
    hostname: 
    restart: 
    networks:
      video_net:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=docker
    healthcheck:
     test: 
     interval: 5s
     timeout: 10s
     retries: 3
    ports:

  smart-home-mysql-dev:
    image: mysql:5.7
    volumes:
    environment: 
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    networks:
      video_net:

networks:
  video_net:
    driver: bridge
