version: '3.4'

services:
  smart-home-front:
    image: 
    container_name: 
    hostname: 
    restart: always
    networks:
      video_net:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=docker
    healthcheck:
     test: curl -sS http://127.0.0.1:80 || echo 1
     interval: 5s
     timeout: 10s
     retries: 3
    ports:
      - 98:80


networks:
  video_net:
    driver: bridge
